#=== General
#==============================================================================================
- name: general | set sidebar icon size to small
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSTableViewDefaultSizeMode
    type:   int
    value:  1
